# Generated by Django 4.2.5 on 2024-01-03 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0008_weapon_image_alter_weapon_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('MEDICAL', 'Medicina'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('MEDICAL', 'Medicina'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20),
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1)),
                ('coverage', models.CharField(choices=[('HEAD', 'Cabeza'), ('TORSO', 'Torso'), ('UPPER', 'Torso y Brazos'), ('LOWER', 'Piernas'), ('BODY', 'Cuerpo'), ('FULL', 'Todo')], default='BODY', max_length=20)),
                ('type', models.CharField(choices=[('L', 'Blando'), ('H', 'Duro')], default='H', max_length=1)),
                ('sp', models.IntegerField()),
                ('ev', models.IntegerField()),
                ('weight', models.FloatField()),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
            ],
        ),
    ]
