# Generated by Django 4.2.5 on 2024-01-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0010_alter_armor_type_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NO', 'No Aplica'), ('IN', 'Insignificante'), ('SE', 'Secundaria'), ('IM', 'Importante'), ('CR', 'Crítica')], max_length=2)),
                ('difficulty', models.IntegerField()),
                ('time_length', models.IntegerField()),
                ('damage', models.CharField(default='No', max_length=10)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cyberware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1)),
                ('type', models.CharField(choices=[('OPT', 'Opcional')], default='OPT', max_length=5)),
                ('humanity', models.CharField(max_length=10, null=True)),
                ('requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment', models.CharField(blank=True, max_length=100, null=True)),
                ('slot', models.CharField(choices=[('FUL', 'Cuerpo y Cabeza'), ('HEA', 'Cabeza'), ('BOD', 'Cuerpo'), ('TOR', 'Torso'), ('ARM', 'Brazo'), ('CRO', 'Ingle'), ('LEG', 'Pierna')], default='FUL', max_length=3)),
                ('weight', models.FloatField()),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.surgery')),
            ],
        ),
    ]
