# Generated by Django 4.2.5 on 2024-01-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0011_surgery_cyberware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberware',
            name='slot',
            field=models.CharField(choices=[('FUL', 'Cuerpo y Cabeza'), ('HEA', 'Cabeza'), ('BOD', 'Cuerpo'), ('TOR', 'Torso'), ('ARM', 'Brazo'), ('AOL', 'Brazo o Pierna'), ('LEG', 'Pierna'), ('CRO', 'Ingle')], default='FUL', max_length=3),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='type',
            field=models.CharField(choices=[('IMP', 'Implante'), ('EXT', 'Externo'), ('ADD', 'Opción'), ('IMPRO', 'Mejora'), ('MRAM', 'Chip de Memoria'), ('CPART', 'Chip de Reflejos')], default='IMP', max_length=5),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1)),
                ('type', models.CharField(choices=[('U', 'Unisex'), ('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Sin Tipo')], default='N', max_length=3)),
                ('weight', models.FloatField()),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
            ],
        ),
    ]
