# Generated by Django 4.2.5 on 2024-01-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0012_alter_cybersurgery_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CyberSurgery',
            new_name='Surgery',
        ),
    ]
