# Generated by Django 4.2.5 on 2024-01-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0012_alter_cyberware_slot_alter_cyberware_type_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficult', models.IntegerField()),
                ('decription', models.CharField(max_length=255, null=True)),
                ('overdose_decription', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diff_modifier', models.IntegerField()),
                ('decription', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('DRUGS', 'Drogas'), ('MEDICAL', 'Cuidados Médicos'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('DRUGS', 'Drogas'), ('MEDICAL', 'Cuidados Médicos'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('B', 'Bebidas Alcohólicas'), ('C', 'Cigarrillos'), ('M', 'Medicina'), ('D', 'Droga')], default='D', max_length=3)),
                ('form', models.CharField(choices=[('P', 'Píldora o Tableta'), ('G', 'Cápsula'), ('T', 'Pestaña de Papel'), ('S', 'Fumado, Inhalado'), ('PI', 'En polvo, Inhalado'), ('I', 'Inyectado'), ('L', 'Líquido'), ('B', 'Parche'), ('C', 'Contacto')], default='P', max_length=3)),
                ('legaility', models.CharField(choices=[('L', 'De venta legal'), ('P', 'Solo por prescripción'), ('C', 'Ilegal tipo C'), ('B', 'Ilegal tipo B'), ('A', 'Ilegal tipo A'), ('E', 'Experimental')], default='L', max_length=3)),
                ('strength', models.IntegerField()),
                ('dosis', models.CharField(max_length=20)),
                ('presentation', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=20)),
                ('effects_description', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('side_effects_description', models.CharField(max_length=255, null=True)),
                ('overdose', models.CharField(max_length=20)),
                ('overdose_description', models.CharField(max_length=255, null=True)),
                ('addiction', models.CharField(choices=[('PH', 'Fisiológica'), ('PS', 'Sicológica')], default='PH', max_length=3)),
                ('addiction_level', models.IntegerField()),
                ('next_dose', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('decription', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category')),
                ('effects', models.ManyToManyField(to='cpadmin.drugeffect')),
                ('side_effects', models.ManyToManyField(to='cpadmin.drugsideeffect')),
            ],
        ),
    ]
