# Generated by Django 4.2.5 on 2024-01-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0013_drugeffect_drugsideeffect_alter_brand_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='legaility',
            new_name='legality',
        ),
    ]
