# Generated by Django 4.2.5 on 2024-01-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0014_rename_legaility_drug_legality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='overdose',
        ),
    ]
