# Generated by Django 4.2.5 on 2024-01-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0015_remove_drug_overdose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='addiction_level',
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='decription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='overdose_decription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
