# Generated by Django 4.2.5 on 2024-01-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0016_remove_drug_addiction_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugsideeffect',
            name='decription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
