# Generated by Django 4.2.5 on 2024-01-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0017_alter_drugsideeffect_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='decription',
            new_name='description',
        ),
    ]
