# Generated by Django 4.2.5 on 2024-01-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0018_rename_decription_drug_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DOC', 'Visita a Médico'), ('CLI', 'Visita a Centro Médico'), ('HOS', 'Visita a Hospital'), ('INT', 'Hospitalización'), ('SUR', 'Cirugía'), ('TER', 'Terapia'), ('MED', 'Uso de Medicina')], default='DOC', max_length=3)),
                ('quality', models.CharField(choices=[('VL', 'Muy Baja'), ('L', 'Baja'), ('N', 'Normal'), ('H', 'Alta'), ('VH', 'Muy Alta')], default='N', max_length=3)),
                ('elapsed_time', models.IntegerField()),
                ('elapsed_time_uom', models.CharField(choices=[('SEC', 'Segundos'), ('MIN', 'Minutos'), ('HRS', 'Horas'), ('D', 'Días'), ('W', 'Semanas'), ('M', 'Meses'), ('Q', 'Trimestres'), ('Y', 'Años')], default='HRS', max_length=3)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='image',
        ),
    ]
