# Generated by Django 4.2.5 on 2024-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0019_medical_remove_drug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='effects_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='overdose_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='side_effects_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(choices=[('B', 'Bebidas Alcohólicas'), ('C', 'Cigarrillos'), ('M', 'Fármaco'), ('D', 'Droga')], default='D', max_length=3),
        ),
    ]
