# Generated by Django 4.2.5 on 2024-01-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0023_rename_acc_vehicle_acceleration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
    ]
