# Generated by Django 4.2.5 on 2024-01-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0024_alter_vehicle_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armor',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drug',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medical',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
