# Generated by Django 4.2.5 on 2024-01-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0025_alter_armor_cost_alter_armor_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('L', 'Vehículos Terrestres'), ('A', 'Vehículos Aéreos'), ('W', 'Vehículos Acuáticos'), ('S', 'Vehículos Espaciales')], default='L', max_length=1),
        ),
    ]
