# Generated by Django 4.2.5 on 2024-01-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0026_alter_vehicle_name_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='coverage',
            field=models.CharField(choices=[('HEAD', 'Cabeza'), ('TORSO', 'Torso'), ('UPPER', 'Torso y Brazos'), ('LOWER', 'Piernas'), ('BODY', 'Cuerpo'), ('FULL', 'Todo')], default='BODY', max_length=20, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='ev',
            field=models.IntegerField(verbose_name='CE'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='sp',
            field=models.IntegerField(verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='type',
            field=models.CharField(choices=[('S', 'Blando'), ('H', 'Duro')], default='H', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Sin Tipo')], default='N', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='adjustment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ajustes'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='humanity',
            field=models.CharField(max_length=10, null=True, verbose_name='Costo Humanidad'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='requirement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Requisito'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='slot',
            field=models.CharField(choices=[('FUL', 'Cuerpo y Cabeza'), ('HEA', 'Cabeza'), ('BOD', 'Cuerpo'), ('TOR', 'Torso'), ('ARM', 'Brazo'), ('AOL', 'Brazo o Pierna'), ('LEG', 'Pierna'), ('CRO', 'Ingle')], default='FUL', max_length=3, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.surgery', verbose_name='Tipo de Cirugía'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='type',
            field=models.CharField(choices=[('IMP', 'Implante'), ('EXT', 'Externo'), ('ADD', 'Opción'), ('IMPRO', 'Mejora'), ('MRAM', 'Chip de Memoria'), ('CPART', 'Chip de Reflejos')], default='IMP', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='addiction',
            field=models.CharField(choices=[('PH', 'Fisiológica'), ('PS', 'Sicológica')], default='PH', max_length=3, verbose_name='Tipo de Adicción'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosis',
            field=models.CharField(max_length=20, verbose_name='Dosis'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='duration',
            field=models.CharField(max_length=20, verbose_name='Duración Efectos'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(to='cpadmin.drugeffect', verbose_name='Efectos'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Efectos'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='form',
            field=models.CharField(choices=[('P', 'Píldora o Tableta'), ('G', 'Cápsula'), ('T', 'Pestaña de Papel'), ('S', 'Fumado, Inhalado'), ('PI', 'En polvo, Inhalado'), ('I', 'Inyectado'), ('L', 'Líquido'), ('B', 'Parche'), ('C', 'Contacto')], default='P', max_length=3, verbose_name='Forma'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='legality',
            field=models.CharField(choices=[('L', 'De venta legal'), ('P', 'Solo por prescripción'), ('C', 'Ilegal tipo C'), ('B', 'Ilegal tipo B'), ('A', 'Ilegal tipo A'), ('E', 'Experimental')], default='L', max_length=3, verbose_name='Legilidad'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='next_dose',
            field=models.CharField(max_length=50, verbose_name='Tiempo Siguiente Dosis'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='overdose_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobredosis'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='presentation',
            field=models.CharField(max_length=50, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(to='cpadmin.drugsideeffect', verbose_name='Efectos Secundarios'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='side_effects_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de Efectos Secundarios'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='speed',
            field=models.CharField(max_length=20, verbose_name='Velocidad de Efecto'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.IntegerField(verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='symptoms',
            field=models.CharField(max_length=50, verbose_name='Tiempo Síntomas'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(choices=[('B', 'Bebidas Alcohólicas'), ('C', 'Cigarrillos'), ('M', 'Fármaco'), ('D', 'Droga')], default='D', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=models.CharField(choices=[('OPT', 'Opcional')], default='OPT', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='elapsed_time',
            field=models.IntegerField(verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='elapsed_time_uom',
            field=models.CharField(choices=[('SEC', 'Segundos'), ('MIN', 'Minutos'), ('HRS', 'Horas'), ('D', 'Días'), ('W', 'Semanas'), ('M', 'Meses'), ('Q', 'Trimestres'), ('Y', 'Años')], default='HRS', max_length=3, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='quality',
            field=models.CharField(choices=[('VL', 'Muy Baja'), ('L', 'Baja'), ('N', 'Normal'), ('H', 'Alta'), ('VH', 'Muy Alta')], default='N', max_length=3, verbose_name='Calidad'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='type',
            field=models.CharField(choices=[('DOC', 'Visita a Médico'), ('CLI', 'Visita a Centro Médico'), ('HOS', 'Visita a Hospital'), ('INT', 'Hospitalización'), ('SUR', 'Cirugía'), ('TER', 'Terapia'), ('MED', 'Uso de Medicina')], default='DOC', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='damage',
            field=models.CharField(default='No', max_length=10, verbose_name='Daño'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='difficulty',
            field=models.IntegerField(verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='time_length',
            field=models.IntegerField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='type',
            field=models.CharField(choices=[('NO', 'No Aplica'), ('IN', 'Insignificante'), ('SE', 'Secundaria'), ('IM', 'Importante'), ('CR', 'Crítica')], max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='acceleration',
            field=models.IntegerField(default=0, verbose_name='Aceleración'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cargo',
            field=models.IntegerField(default=0, verbose_name='Carga'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='crew',
            field=models.IntegerField(default=1, verbose_name='Tripulación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deceleration',
            field=models.IntegerField(default=0, verbose_name='Desaceleración'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='maneuverability',
            field=models.IntegerField(default=0, verbose_name='Maniobrabilidad'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='passengers',
            field=models.IntegerField(default=0, verbose_name='Pasajeros'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='range',
            field=models.IntegerField(default=0, verbose_name='Autonomía'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sdp',
            field=models.IntegerField(default=0, verbose_name='PDE'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sp',
            field=models.IntegerField(default=0, verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='top_speed',
            field=models.IntegerField(default=0, verbose_name='Velocidad Máxima'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('L', 'Vehículos Terrestres'), ('A', 'Vehículos Aéreos'), ('W', 'Vehículos Acuáticos'), ('S', 'Vehículos Espaciales')], default='L', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy',
            field=models.IntegerField(verbose_name='Precisión'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('E', 'Excelente'), ('C', 'Común'), ('P', 'Mala'), ('R', 'Rara'), ('A', 'Solo Militares'), ('X', 'Experimental')], default='C', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='concealment',
            field=models.CharField(choices=[('P', 'Bolsillo'), ('J', 'Chaqueta'), ('L', 'Chaqueta Larga'), ('N', 'No')], default='J', max_length=2, verbose_name='Disimulo'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.BigIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(max_length=20, verbose_name='Daño'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alcance'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reliability',
            field=models.CharField(choices=[('VR', 'Muy Fiable'), ('ST', 'Fiable'), ('UR', 'Poco Fiable')], default='ST', max_length=2, verbose_name='Fiabilidad'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rof',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disparos por Ronda'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='shots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disparos'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
    ]
