# Generated by Django 4.2.5 on 2024-01-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpadmin', '0027_alter_armor_availability_alter_armor_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='range',
            new_name='autonomy',
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('DRUGS', 'Drogas'), ('MEDICAL', 'Cuidados Médicos'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpadmin.category', verbose_name='padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('WEAPON', 'Armas'), ('ARMOR', 'Blindaje'), ('GEAR', 'Equipo'), ('CYBER', 'Ciberequipo'), ('CLOTHES', 'Moda'), ('DRUGS', 'Drogas'), ('MEDICAL', 'Cuidados Médicos'), ('VEHICLE', 'Vehículos'), ('HARDWARE', 'Periféricos'), ('SOFTWARE', 'Programas')], default='WEAPON', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='legality',
            field=models.CharField(choices=[('L', 'De venta legal'), ('P', 'Solo por prescripción'), ('C', 'Ilegal tipo C'), ('B', 'Ilegal tipo B'), ('A', 'Ilegal tipo A'), ('E', 'Experimental')], default='L', max_length=3, verbose_name='Legalidad'),
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='decription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='difficult',
            field=models.IntegerField(verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='drugeffect',
            name='overdose_decription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobredosis'),
        ),
        migrations.AlterField(
            model_name='drugsideeffect',
            name='decription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='drugsideeffect',
            name='diff_modifier',
            field=models.IntegerField(verbose_name='Modificador'),
        ),
        migrations.AlterField(
            model_name='drugsideeffect',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
