from django.shortcuts import render, redirect, HttpResponse
import csv
from .models import (
    ItemType, Weapon, Category, Brand, Availability, Concealment, Reliability
)
from .config import database


# Show weapon List
def list(request):
    weapons = Weapon.objects.all().order_by('name')
    weapons_count = 0
    if weapons:
        weapons_count = len(weapons)

    categories = Category.objects.filter(type='WEAPON').order_by('name')
    brands = Brand.objects.filter(type='WEAPON').order_by('name')
    availabilities = Availability.choices
    concealments = Concealment.choices
    reliabilities = Reliability.choices

    context = {
        'weapons_count': weapons_count,
        'weapons': weapons,
        'categories': categories,
        'brands': brands,
        'availabilities': availabilities,
        'concealments': concealments,
        'reliabilities': reliabilities,
    }
        
    return render(request, 'equipment/weapons.html', context)


# Create a weapon
def create(request):
    form = request.POST
    category = Category.objects.get(id=form['category'])
    brand = Brand.objects.get(id=form['brand'])
    weapon = Weapon(
        name=form['name'],
        category=category,
        brand=brand,
        availability=form['availability'],
        concealment=form['concealment'],
        accuracy=form['accuracy'],
        reliability=form['reliability'],
        range=float(form['range']) if form['range'] != '' else None,
        shots=int(form['shots']) if form['shots'] != '' else None,
        rof=int(form['rof']) if form['rof'] != '' else None,
        damage=form['damage'],
        weight=float(form['weight']),
        cost=int(form['cost']),
        description=form['description'],
        image=form['image'],
    )
    weapon.save()

    return redirect('weapons')


# Update a weapon
def update(request):
    form = request.POST
    weapon = Weapon.objects.get(id=form['id'])
    category = Category.objects.get(id=form['category'])
    brand = Brand.objects.get(id=form['brand'])
    weapon.name = form['name']
    weapon.category = category
    weapon.brand = brand
    weapon.availability = form['availability']
    weapon.concealment = form['concealment']
    weapon.accuracy = form['accuracy']
    weapon.reliability = form['reliability']
    weapon.range = float(form['range']) if form['range'] != '' else None
    weapon.shots = int(form['shots']) if form['shots'] != '' else None
    weapon.rof = int(form['rof']) if form['rof'] != '' else None
    weapon.damage = form['damage']
    weapon.weight = float(form['weight'])
    weapon.cost = int(form['cost'])
    weapon.description = form['description']
    weapon.image = form['image']
    weapon.save()

    return redirect('weapons')


# Delete a weapon
def delete(request):
    form = request.POST
    weapon = Weapon.objects.get(id=form['id'])
    weapon.delete()

    return redirect('weapons')

# Upload weapons list from CSV
def upload(request):
    csv_file = request.FILES['csv_file'].read().decode('utf-8').splitlines()
    csv_reader = csv.DictReader(csv_file)

    for row in csv_reader:
        category = Category.objects.get(code=row['category'], parent=None)
        brand, _ = Brand.objects.get_or_create(
            name=row['brand'], 
            defaults={'name': row['brand'], 'type': ItemType.WEAPON, 'description': 'Autogenerated'})

        Weapon.objects.update_or_create(
            id=row['id'],
            defaults=dict(
                name=row['name'],
                category=category,
                brand=brand,
                availability=row['availability'],
                concealment=row['concealment'],
                accuracy=row['accuracy'],
                reliability=row['reliability'],
                range=float(row['range']) if row['range'] != '' else None,
                shots=int(row['shots']) if row['shots'] != '' else None,
                rof=int(row['rof']) if row['rof'] != '' else None,
                damage=row['damage'],
                weight=float(row['weight']),
                cost=int(row['cost']),
                description=row['description'],
                image=row['image'],
            )
        )

    return redirect('weapons')


# Download weapon list in CSV
def download(request):
    weapons = Weapon.objects.all().order_by('name').values()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="weapons.csv"'
    csv_writer = csv.writer(response)
    headers = False

    weapons_translated = []
    for weapon in weapons:
        weapon_translated = {}
        keys = weapon.keys()
        for key in keys:
            value = weapon[key]
            if key == 'category_id':
                category = Category.objects.get(id=value)
                weapon_translated['category'] = category.code
            elif key == 'brand_id': 
                brand = Brand.objects.get(id=value)
                weapon_translated['brand'] = brand.name
            else:
                weapon_translated[key] = value
        weapons_translated.append(weapon_translated)
    
    for weapon in weapons_translated:
        if not headers:
            csv_writer.writerow(weapon.keys())
            headers = True
        csv_writer.writerow(weapon.values())
        
    return response


# Refresh weapons list with Firebase
def refresh(request):
    source = request.POST['source']
    if source == 'local': 
        weapons_local = Weapon.objects.all().order_by('id').values()
        database.child('Weapon').remove()
        for weapon in weapons_local:
            database.child('Weapon').push(weapon)
    else:
        weapons_origin = database.child('Weapon').get()
        for weapon_id, weapon in weapons_origin:
            category = Category.objects.get(code=weapon.category, parent=None)
            brand, _ = Brand.objects.get_or_create(
                name=weapon.brand, type=ItemType.WEAPON,
                defaults={'name': weapon.brand, 'type': ItemType.WEAPON, 'description': 'Autogenerated'})
            
            Weapon.objects.update_or_create(
                id=weapon_id,
                defaults=dict(
                    name=weapon.name,
                    category=category,
                    brand=brand,
                    availability=weapon.availability,
                    concealment=weapon.concealment,
                    accuracy=weapon.accuracy,
                    reliability=weapon.realiability,
                    range=weapon.range,
                    shots=weapon.shots,
                    rof=weapon.rof,
                    damage=weapon.damage,
                    weight=weapon.weight,
                    cost=weapon.cost,
                    description=weapon.description,
                    image=weapon.image,
                ),
            )
            
    return redirect('weapons')

    
### Functions for Armor Section

# Show armor list
def armor_list(request):
    armors = Armor.objects.all().order_by('name')
    armor_count = 0
    if armors:
        armor_count = len(armors)

    categories = Category.objects.filter(type='ARMOR').order_by('name')
    brands = Brand.objects.filter(type='ARMOR').order_by('name')
    availabilities = Availability.choices
    armor_types = ArmorType.choices
    coverages = Coverage.choices

    context = {
        'armor_count': armor_count,
        'armors': armors,
        'categories': categories,
        'brands': brands,
        'availabilities': availabilities,
        'armor_types': armor_types,
        'coverages': coverages,
    }
        
    return render(request, 'equipment/armor.html', context)


# Create an armor
def armor_create(request):
    form = request.POST
    category = Category.objects.get(id=form['category'])
    brand = Brand.objects.get(id=form['brand'])
    armor = Armor(
        name=form['name'],
        category=category,
        brand=brand,
        availability=form['availability'],
        coverage=form['coverage'],
        type=form['type'],
        sp=int(form['sp']) if form['sp'] != '' else None,
        ev=int(form['ev']) if form['ev'] != '' else None,
        weight=float(form['weight']),
        cost=int(form['cost']),
        description=form['description'],
        image=form['image'],
    )
    armor.save()

    return redirect('armor')


# Update an armor
def armor_update(request):
    form = request.POST
    armor = Armor.objects.get(id=form['id'])
    category = Category.objects.get(id=form['category'])
    brand = Brand.objects.get(id=form['brand'])
    armor.name = form['name']
    armor.category = category
    armor.brand = brand
    armor.coverage = form['coverage']
    armor.type = form['type']
    armor.sp = int(form['sp']) if form['sp'] != '' else None
    armor.ev = int(form['ev']) if form['ev'] != '' else None
    armor.weight = float(form['weight'])
    armor.cost = int(form['cost'])
    armor.description = form['description']
    armor.image = form['image']
    armor.save()
    
    return redirect('armor')


# Delete an armor
def armor_delete(request):
    form = request.POST
    armor = Armor.objects.get(id=form['id'])
    armor.delete()
    return redirect('armor')


# Upload armor list from CSV
def armor_upload(request):
    csv_file = request.FILES['csv_file'].read().decode('utf-8').splitlines()
    csv_reader = csv.DictReader(csv_file)

    for row in csv_reader:
        category = Category.objects.get(name=row['category'], parent=None)
        brand, _ = Brand.objects.get_or_create(
            name=row['brand'], type=ItemType.ARMOR,
            defaults={'name': row['brand'], 'type': ItemType.ARMOR, 'description': 'Autogenerated'})

        Armor.objects.update_or_create(
            id=row['id'],
            defaults=dict(
                name=row['name'],
                category=category,
                brand=brand,
                availability=row['availability'],
                coverage=row['coverage'],
                type=row['type'],
                sp=int(row['sp']) if row['sp'] != '' else None,
                ev=int(row['ev']) if row['ev'] != '' else None,
                weight=float(row['weight']),
                cost=int(row['cost']),
                description=row['description'],
                image=row['image'],
            )
        )
        
    return redirect('armor')


# Download armor list in CSV
def armor_download(request):
    armors = Armor.objects.all().order_by('name').values()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="armors.csv"'
    csv_writer = csv.writer(response)
    headers = False

    armors_translated = []
    for armor in armors:
        armor_translated = {}
        keys = armor.keys()
        for key in keys:
            value = armor[key]
            if key == 'category_id':
                category = Category.objects.get(id=value)
                armor_translated['category'] = category.code
            elif key == 'brand_id': 
                brand = Brand.objects.get(id=value)
                armor_translated['brand'] = brand.name
            else:
                armor_translated[key] = value
        armors_translated.append(armor_translated)
    
    for armor in armors_translated:
        if not headers:
            csv_writer.writerow(armor.keys())
            headers = True
        csv_writer.writerow(armor.values())
        
    return response


# Refresh armor list with Firebase
def armor_refresh(request):
    source = request.POST['source']
    if source == 'local': 
        armor_local = Armor.objects.all().order_by('id').values()
        database.child('Armor').remove()
        for armor in armor_local:
            database.child('Armor').push(armor)
    else:
        armor_origin = database.child('Armor').get()
        for armor_id, armor in armor_origin:
            category = Category.objects.get(code=armor.category, parent=None)
            brand, _ = Brand.objects.get_or_create(
                name=armor.brand, 
                defaults={'name': armor.brand, 'type': ItemType.ARMOR, 'description': 'Autogenerated'})
            
            Weapon.objects.update_or_create(
                id=armor_id,
                defaults=dict(
                    name=armor.name,
                    category=category,
                    brand=brand,
                    availability=armor.availability,
                    coverage=armor.coverage,
                    type=armor.typr,
                    sp=armor.sp,
                    ev=armor.ev,
                    weight=armor.weight,
                    cost=armor.cost,
                    description=armor.description,
                    image=armor.image,
                ),
            )

    return redirect('armor')
